# Generated by Django 6.0.3 on 2026-05-21 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly title (e.g., lisbon-q2-report)', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('market', 'Market Intelligence'), ('guides', 'Neighbourhood Guides'), ('explained', 'CRE Explained')], default='market', max_length=20)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for the homepage card.')),
                ('content', models.TextField(help_text='Paste your Google Doc content here. HTML is supported.')),
                ('seo_title', models.CharField(blank=True, help_text='Overrides title for search engines if provided.', max_length=255)),
                ('seo_description', models.TextField(blank=True, help_text='Meta description for Google.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalityNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('score_accessibility', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('score_lifestyle', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('score_commercial', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MacroInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='Lisbon', max_length=255)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metric_unit', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('recorded_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('source_platform', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('size_sqm', models.IntegerField(blank=True, null=True)),
                ('data_freshness_tier', models.CharField(choices=[('TIER_1', 'Tier 1 (Green) - Live API/Verified'), ('TIER_2', 'Tier 2 (Yellow) - Scraped < 30 Days'), ('TIER_3', 'Tier 3 (Grey) - Scraped > 45 Days')], default='TIER_2', max_length=20)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('marketplace', 'Marketplace'), ('private', 'Private')], default='public', max_length=20)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='urbaty.localitynode')),
            ],
        ),
    ]
