# Generated by Django 6.0.3 on 2026-04-21 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('locality_score', models.JSONField(blank=True, help_text='Stores Maps/Transit API data', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='inventory.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('desk', 'Dedicated Desk'), ('private_office', 'Private Office'), ('meeting_room', 'Meeting Room'), ('virtual_office', 'Virtual Office')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', help_text='Physical status only. Occupancy is derived.', max_length=20)),
                ('visibility_level', models.CharField(choices=[('private', 'Private (Internal Only)'), ('marketplace', 'Marketplace (Logged-in)'), ('public', 'Public (Fully Indexed)')], default='private', max_length=20)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.space')),
            ],
        ),
    ]
